//------------------------------------------------------------------------------
// <auto-generated>
// The code was machine generated.
// Runtime version: 4.0.30319.42000
//
// Changes made to this file can cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCleanerUpdater.Properties {
    using System;


    /// <summary>
         /// Strongly typed resource class for finding localized strings and so on.
    /// </summary>
    // This class was automatically generated by the StronglyTypedResourceBuilder class.
    // via a tool such as ResGen or Visual Studio.
    // To add or remove a member, edit the ResX file and run ResGen again
    // with the /str option or recompile the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached instance of ResourceManager used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCleanerUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///  Overrides the CurrentUICulture property of the current thread for
        ///  all resource searches performed using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Search for a localized string similar to
        ///   <?xml version="1.0" encoding="UTF-16"?>
        //<Task version = "1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
        //  <RegistrationInfo>
        //    <URI>\CCleanerUpdater</URI>
        //  </RegistrationInfo>
        //  <Triggers>
        //    <LogonTrigger>
        //      <Enabled>true</Enabled>
        //      <Delay>PT5M</Delay>
        //    </LogonTrigger>
        //  </Triggers>
        //  <Principals>
        //    <Principal id = "Author" >
        //      < LogonType > InteractiveToken </ LogonType >
        //      < RunLevel > HighestAvailable </ RunLevel >
        //    </ Principal >
        //  </ Principals >
        //  < Settings >
        //    < MultipleInstancesPolicy > IgnoreNew </ MultipleInstancesPolicy >
        //    < DisallowStartIfOnBatteries > false </ DisallowStartIfOnBatteries >
        //    < StopIfGoingOnBatteries > false </ StopIfGoingOnBatteries >
        //    < AllowHardTerminate > true </ AllowHardTerminate >
        //    < StartWhenAvailable > true </ StartWhenAvailable >
        //    < RunOnlyIfNetworkAvailable > false </ RunOnlyIfNetworkAvailable >
        //    < IdleSettings >
        //      < StopOnIdleEnd > true </ StopOnIdleEnd >
        //      < RestartOnIdle > false </ RestartOnIdle >
        //    </ IdleSettings >
        //    < AllowStartOnDemand > true </ AllowStartOnDemand >
        //    < Enabled > true </ Enabled >
        //    < Hidden > false </ Hidden >
        //    < RunOnlyIfIdle > false </ RunOnlyIfIdle >
        //    < DisallowStartOnRemoteAppSession > false </ DisallowStartOnRemoteAppSession >
        //    < UseUnifiedSchedulingEngine > true </ UseUnifiedSchedulingEngine >
        //    < WakeToRun > false </ WakeToRun >
        //    < ExecutionTimeLimit > PT8H </ ExecutionTimeLimit >
        //    < Priority > 7 </ Priority >
        //  </ Settings >
        //  < Actions Context="Author">
        //    <Exec>
        //      <Command>%PATH_TO_TOOL%</Command>
        //      <Arguments>%ARG_TO_USE%</Arguments>
        //    </Exec>
        //  </Actions>
        //</Task>
        /// </summary>
        internal static string CCleanerUpdaterService {
            get {
                return ResourceManager.GetString("CCleanerUpdaterService", resourceCulture);
            }
        }
    }
}
